### ISSUE TITLE
Duplicating an artboard switches original and duplicate artboard in Prott.

### ISSUE THREAD

**Issue by gersomvg** [goodpatch/Prott-Sketch-Plugin#1]
Firstly, thanks for creating this plugin! It is central to my ultra fast prototyping workflow, in which I have custom symbols in Sketch, which I combine onto artboards, and then sync to prott for clickable prototypes.

But there is one thing that bothers me in this workflow. See this:
- Create artboard1 and sync it to prott
- Duplicate artboard1 using right click + duplicate or by option-dragging
- Sync both artboards
- You will now see that the artboard1 is replaced with its duplicate and the original has become a new instance in Prott

This is not the case when using copy paste to duplicate an artboard.

**Comment by haseda** [comment]
Thanks for contacting us regarding your inquiry. We sincerely apologize for the delay in getting back to you.

Regarding your inquiry, I believe this already been resolved with Sketch.

If this does continue to persist, please let us know.
