### ISSUE TITLE
SketchからProttのプロジェクトへSyncしようとすると、エラーが発生してしまう

### ISSUE THREAD

**Issue by i104** [goodpatch/Prott-Sketch-Plugin#4]
# Why (サポート依頼時は記載なくて良い)

## 概要 / Overview
- 「Prott Sketch Plugin」を使用してProttにSyncしようとすると、以下のエラー画面が表示され強制終了しないといけなくなるとのこと  
<img width="420" alt="2017-12-27 15 33 49" src="https://user-images.githubusercontent.com/20853342/34373573-3e565748-eb1f-11e7-8a37-0abf8fb26496.png">  

- 追加しているSketch Pluginは、2.0.4なので現在の最新    
<img width="521" alt="2017-12-27 15 23 14" src="https://user-images.githubusercontent.com/20853342/34373584-4af56232-eb1f-11e7-8657-317767582a52.png">

- ProttアカウントはFreeプランだけど、マイアカウントには自身がオーナーのプロジェクトが1つのみ  
- zeplinへ連携し、そこからpngでダウンロードした場合、いずれも画像の容量は1Mもない（参考程度）  
- Sketchの再起動やPluginからのLogout→Loginは実施済みだが改善せず  
- Sketch のバージョンは、48.2  
- HDDの空き容量は「469.54GB」  
- テンポラリフォルダの設定は変更しておりません。  
  - ライブラリの配下を色々見ていたので、意図せず変更してしまった可能性はあるらしい  

## 再現手順
1. sketchのメニューバー「Plugins」>「Prott Sketch Plugin」>「Sync All Artboards to Prott」と選択
2. 「sync」をクリックする

## その他
sketch→prott、sketch→Zeplinへ連携するため、それぞれのプラグインを追加していて、Zeplinは連携できているとのこと

## 関連リンク / Related Link
- Intercom
https://app.intercom.io/a/apps/a3806aabecf009f8a9cf714bd99e26c18f16883f/respond/inbox/all/conversations/13763783603
- CMS
yamamoto_chihiro@intec.co.jp
https://prottapp.com:10443/cms/#/user/5a02bfb386e4657f0ac8eb46
- SyncさせようとしているプロジェクトのURL
https://prottapp.com/app/#/projects/5a02bfd286e4650278c8e749

**Comment by i104** [comment]
@koyachi @ymegane 
このエラーの現象について、原因をご確認いただけますでしょうか？

**Comment by koyachi** [comment]
無理矢理再現させる方法は１つ見つけました。

今回再現した方法によると、テンポラリフォルダ以下に画像を正しく保存できていないか、正しく保存は出来ているが読み込みていないか、のような気がします。

# 再現コード
```diff
172-3-11-53:prott-sketch-plugin-private koyachi$ git diff
diff --git a/prott.sketchplugin/Contents/Sketch/core.cocoascript b/prott.sketchplugin/Contents/Sketch/core.cocoascript
index b8a6466..46039f1 100755
--- a/prott.sketchplugin/Contents/Sketch/core.cocoascript
+++ b/prott.sketchplugin/Contents/Sketch/core.cocoascript
@@ -713,9 +713,9 @@ var prott = {
         [copy removeFromParent]
         slice.scale = prott.getSavedValueFromKey("ratio")
         slice.format = "png"
-        var filePath = NSTemporaryDirectory() + "prott/" + artboard.objectID() + ".png"
-        [document saveArtboardOrSlice:slice toFile: filePath]
-//        var filePath = NSTemporaryDirectory() + "prott/" + "sonzai-sinai-path" + ".png" => 再現した
+//        var filePath = NSTemporaryDirectory() + "prott/" + artboard.objectID() + ".png"
+//        [document saveArtboardOrSlice:slice toFile: filePath]
+        var filePath = NSTemporaryDirectory() + "prott/" + "sonzai-sinai-path" + ".png" //=> 再現した

         var task = NSTask.alloc().init()
         task.setLaunchPath("/usr/bin/curl")
172-3-11-53:prott-sketch-plugin-private koyachi$
```

再現した様子
![image](https://user-images.githubusercontent.com/19330/34373793-c1f24908-eb20-11e7-8141-477be5b5365d.png)

@i104 お客様にはディスク容量大丈夫か、テンポラリフォルダの設定いじってないか、保存or読み込みに影響しそうなアートボードの内容になってないか（容量小さいというやりとり見るとこれは無いかな…）あたりを聞いてもらってもいいでしょうか？

**Comment by koyachi** [comment]
アートボードの名称が変わってる（ファイルパスに適さない）可能性もありそう

**Comment by i104** [comment]
@koyachi ありがとうございます！ちょっと確認してみますー
あと、Pluginの削除インストールもその後試してもらおうかとも思います。

**Comment by i104** [comment]
アートボードの名称については、仕様的に以下になっているとのことだったので、たぶん大丈夫だと思います。
```
Sketchの アートボードの名前ではなく、アートボードに割り当てられている固有のIDから判別してProttのスクリーンと同期しています。そのため、同名のアートボードをアップロードすることができます。
```

**Comment by koyachi** [comment]
> アートボードの名称については、仕様的に以下になっているとのことだったので、たぶん大丈夫だと思います。

azs!ぼくのほうでも絵文字や"/"が入ってる名称でも問題なくアップロードできることを確認しました。

---

syncする直前にwifiオフにすることでも同じ症状が再現することを確認しましたが、お問い合わせできてるのでネットワーク接続は問題ないだろうし、prottapp.comへの接続が制限されてる状態も再ログインできてることから考えにくいですね。。

**Comment by i104** [comment]
@koyachi 
Pluginの削除インストールも試していただいたのですが、結果的に解決しませんでした。
しばらくは、Sketchから画像で書き出してProttにアップロードしていただく方法などで回避をお願いしております。

来年1/4 or 1/5に状況について連絡をするお約束をして、本日の対応は終了してますー
引き続きご確認をお願いいたします！

**Comment by i104** [comment]
@yahharo 
Sketch PluginでSyncしようとすると、「Projectが存在するか」or「編集権限があるかどうか」確認してねエラーが発生しております。現在こやちさんにお調べいただいているのですが、原因がまだわかっていません。

このお客さまがもっているプロジェクトはCMSに上で見ても、お客さま自身に見ていただいても1つしかない（オーナー権限のものが）のですが、他にオーナー権限のプロジェクトがないかご確認いただくことは可能でしょうか？

ProttはFreeアカウントなので、他にオーナー権限のプロジェクトがあるとSyncできなくなるのではないかと考えています。

作成されているプロジェクト数に問題がなければ、現在の進捗についてお客さまにご連絡して、来週こやちさんが出勤されてから改めてお調べいただく予定です。

お手すきの際で大丈夫ですので、よろしくお願いいたします！

**Comment by i104** [comment]
矢原さんは時間なさそうなご様子だったのと、お客さまもお急ぎではなかったことから現在も調査中である旨返答しました。

**Comment by i104** [comment]
@koyachi すみませんー。こちらの件って何か進捗ありますでしょうか？
他にお客さまに確認が必要なことや、自分の方でもできることがあれば教えてくださいー＞＜

**Comment by koyachi** [comment]
@i104 プラグイン自体の問題かどうかの調査はほとんど進んでないんですが、過去のslackを参考にするとお客様側の環境にプロクシサーバがある可能性があります
https://goodpatch.slack.com/archives/C0YM3QD26/p1498823972513805

同じネットワーク内の他のPCから同じ操作を試して同じ症状が出ればネットワーク環境(かプラグイン自体の問題)であることは切り分けられそうです。再現しなければお客様が最初に使っていたPC環境固有の問題だと思います。

**Comment by i104** [comment]
@koyachi なるほどです！承知しました。ありがとうございます。ちょっと確認してみまする。

**Comment by i104** [comment]
@koyachi 
原因はプロキシでした。設定が入っていたので、お客さまが自主的にスマホ＋テザリングで同期を取ってくださって、正常に動作することを確認しました。プロキシを介さずにネットに繋ぐのは社内規定上無理だったので（ですよね）、その点を踏まえた回避手段として、お客さまに以下の内容をご提案しました。

```
設定方法については、現状2つあるのですが、どちらもProttでの設定ではなく
お客さまのmacやネットワーク環境の設定となります。

mac上の設定の場合は、先程もお話に上がりました
「プロキシ設定を使用しないホストとドメイン」に
「prottapp.com」を追加していただき回避できるかどうかとなります。

また、ネットワーク管理者の方にご対応いただく場合、ProttのWebサービスへアクセス
するときは、プロキシサーバを経由せず接続できるように対応していただく必要があります。

どちらもプロキシサーバを経由せずにProttに接続できるようにするための設定と
なりますので、ネットワーク管理者の方に設定ができるかどうかご確認いただきつつ、
操作を行っていただけますでしょうか？
```

ネットワーク管理者の方に確認しつつ対応してくださるとのことだったので、たぶん本件はこのままクローズになると思います。越年してのご対応ありがとうございました！

**Comment by hanamiju** [comment]
お疲れ様ですー。
ここはPublicなリポジトリなのでPrivateな方でやりとりされた方がいいかも...😅

**Comment by i104** [comment]
@hanamiju ご指摘ありがとうございましたー！
